name : Hello World Workflow
on :
  push:
    branches:
      - main
jobs: 
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses : action/checkout@v4
      - name : Hello world
        run : echo " Hello world"
        shell : bash 
    
