name : Hello World Workflow

on :
  push:
    branches : 
      - main
  pull_request :
    branches:
      - main
      
jobs: 
  hello :
    runs-on :  ubuntu-latest
    steps :
      - uses : actions/checkout@v4
      - name : hello world
        run : echo "Hello World from Samson "
        shell : bash 
  goodbye :
    runs-on : ubuntu-latest
    steps:
      - name  : Goodbye
        run : echo "Goodbye team "
        shell : bash
      
